import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { describe, expect, it } from 'vitest'
import { DOCTOR_PROTOCOL_VERSION, type SupervisorRequest } from '../src/core/protocol.ts'
import { DoctorSupervisor } from '../src/agent/supervisor.ts'
import { doctorPaths } from '../src/agent/paths.ts'

const PROFILE_PATCH = `# AUTO-GENERATED by scripts/aggregate.mjs — do not edit

# from ../dsh-usage
- insert:
    - id: web-ui-usage
      name: '@linxin666/dsh-web-all'
      config:
        plugin: '@linxin666/dsh-usage'

# from ../dsh-i18n
- insert:
    - id: web-ui-i18n
      name: '@linxin666/dsh-i18n'
`

const APPLY_FAILURE_TAIL = [
  'dsh: plugin tree failed to load: failed to apply loader entry include (cordis:include): failed to apply loader entry web-ui-usage (@linxin666/dsh-usage): real plugin start boom',
  'Error: real plugin start boom',
].join('\n')

const UNATTRIBUTED_TAIL = 'EACCES: permission denied, open /home/u/.dsh/profiles/web/settings.yaml\n'

function exitRequest(at: string, stderrTail: string): SupervisorRequest {
  return { protocol: DOCTOR_PROTOCOL_VERSION, type: 'launcher-exit', profileId: 'p1', runId: 'r', exitCode: 1, signal: null, intentional: false, started: false, at, stderrTail }
}

/** The self-heal runs detached (void); wait for supervisor's self heal to settle. */
async function settle(supervisor?: DoctorSupervisor, patchPath?: string, expectedText?: string): Promise<void> {
  if (supervisor?.lastSelfHeal !== undefined) {
    await supervisor.lastSelfHeal.catch(() => undefined)
  }
  for (let i = 0; i < 40; i++) {
    if (patchPath !== undefined && expectedText !== undefined) {
      try {
        const text = await readFile(patchPath, 'utf8')
        if (text.includes(expectedText)) return
      } catch {}
    }
    await new Promise(resolve => setTimeout(resolve, 50))
  }
}

async function setup(options: { autoRepair?: boolean } = {}): Promise<{ dir: string; patchPath: string; supervisor: DoctorSupervisor; paths: ReturnType<typeof doctorPaths> }> {
  const dir = await mkdtemp(join(tmpdir(), 'dsh-doctor-heal-'))
  const home = join(dir, 'home')
  await mkdir(join(home, 'profiles', 'web'), { recursive: true })
  const patchPath = join(home, 'profiles', 'web', 'cordis.patch.yml')
  await writeFile(patchPath, PROFILE_PATCH, 'utf8')
  const paths = doctorPaths({ DSH_DOCTOR_HOME: join(dir, 'doctor') })
  const supervisor = new DoctorSupervisor({ paths })
  await supervisor.start()
  if (options.autoRepair !== false) {
    await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'policy', policy: { fullProtection: true, autoRepair: true, autoMigrate: true } })
  }
  await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'launcher-start', profile: { id: 'p1', dshHome: home, name: 'web', dshExecutable: '/usr/bin/dsh', role: 'protected' }, runId: 'r1', pid: 42, argv: ['dsh', 'web'], at: '2026-01-01T00:00:00Z' })
  return { dir, patchPath, supervisor, paths }
}

describe('supervisor boot self-heal', () => {
  it('first failure only observes; second attributes and disables the row', async () => {
    const { dir, patchPath, supervisor } = await setup()
    try {
      await supervisor.handle(exitRequest('2026-01-01T00:00:10Z', APPLY_FAILURE_TAIL))
      await settle(supervisor)
      let patch = await readFile(patchPath, 'utf8')
      expect(patch).not.toContain('disabled: true')
      const snap1 = (await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'status' })).snapshot!
      expect(snap1.incidents[0]?.evidence.join()).not.toContain('disabled after repeated')
      await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'launcher-start', profile: { id: 'p1', dshHome: join(dir, 'home'), name: 'web', dshExecutable: '/usr/bin/dsh', role: 'protected' }, runId: 'r2', pid: 43, argv: ['dsh', 'web'], at: '2026-01-01T00:01:00Z' })
      await supervisor.handle(exitRequest('2026-01-01T00:01:10Z', APPLY_FAILURE_TAIL))
      await settle(supervisor, patchPath, '# dsh-doctor')
      patch = await readFile(patchPath, 'utf8')
      expect(patch).toContain('# dsh-doctor')
      expect(patch).toContain('- id: web-ui-usage\n  disabled: true')
      expect(patch).toContain("name: '@linxin666/dsh-i18n'") // only the culprit row is touched
      const snap = (await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'status' })).snapshot!
      expect(snap.incidents[0]?.evidence.join()).toContain('self-heal: web-ui-usage')
      expect(snap.incidents[0]?.evidence.join()).toContain('failed to apply loader entry web-ui-usage')
    } finally {
      await supervisor.stop()
      await rm(dir, { recursive: true, force: true })
    }
  })

  it('does not disable anything when the failure cannot be attributed', async () => {
    const { dir, patchPath, supervisor } = await setup()
    try {
      await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'launcher-start', profile: { id: 'p1', dshHome: join(dir, 'home'), name: 'web', dshExecutable: '/usr/bin/dsh', role: 'protected' }, runId: 'r1', pid: 42, argv: ['dsh', 'web'], at: '2026-01-01T00:00:00Z' })
      await supervisor.handle(exitRequest('2026-01-01T00:00:10Z', UNATTRIBUTED_TAIL))
      await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'launcher-start', profile: { id: 'p1', dshHome: join(dir, 'home'), name: 'web', dshExecutable: '/usr/bin/dsh', role: 'protected' }, runId: 'r2', pid: 43, argv: ['dsh', 'web'], at: '2026-01-01T00:01:00Z' })
      await supervisor.handle(exitRequest('2026-01-01T00:01:10Z', UNATTRIBUTED_TAIL))
      await settle(supervisor)
      const patch = await readFile(patchPath, 'utf8')
      expect(patch).not.toContain('disabled: true')
      const snap = (await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'status' })).snapshot!
      expect(snap.incidents[0]?.evidence.join()).toContain('could not be attributed')
    } finally {
      await supervisor.stop()
      await rm(dir, { recursive: true, force: true })
    }
  })

  it('stays silent when autoRepair or fullProtection is off or the profile is paused', async () => {
    const { dir, patchPath, supervisor } = await setup({ autoRepair: false })
    try {
      await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'action', action: 'pause' })
      await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'launcher-start', profile: { id: 'p1', dshHome: join(dir, 'home'), name: 'web', dshExecutable: '/usr/bin/dsh', role: 'protected' }, runId: 'r1', pid: 42, argv: ['dsh', 'web'], at: '2026-01-01T00:00:00Z' })
      await supervisor.handle(exitRequest('2026-01-01T00:00:10Z', APPLY_FAILURE_TAIL))
      await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'launcher-start', profile: { id: 'p1', dshHome: join(dir, 'home'), name: 'web', dshExecutable: '/usr/bin/dsh', role: 'protected' }, runId: 'r2', pid: 43, argv: ['dsh', 'web'], at: '2026-01-01T00:01:00Z' })
      await supervisor.handle(exitRequest('2026-01-01T00:01:10Z', APPLY_FAILURE_TAIL))
      const patch = await readFile(patchPath, 'utf8')
      expect(patch).not.toContain('disabled: true')
    } finally {
      await supervisor.stop()
      await rm(dir, { recursive: true, force: true })
    }
  })

  it('never touches a crash after startup (started=true is not a boot failure)', async () => {
    const { dir, patchPath, supervisor } = await setup()
    try {
      await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'launcher-exit', profileId: 'p1', runId: 'r1', exitCode: 1, signal: null, intentional: false, started: true, at: '2026-01-01T00:00:10Z', stderrTail: APPLY_FAILURE_TAIL })
      await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'launcher-start', profile: { id: 'p1', dshHome: join(dir, 'home'), name: 'web', dshExecutable: '/usr/bin/dsh', role: 'protected' }, runId: 'r2', pid: 43, argv: ['dsh', 'web'], at: '2026-01-01T00:01:00Z' })
      await supervisor.handle({ protocol: DOCTOR_PROTOCOL_VERSION, type: 'launcher-exit', profileId: 'p1', runId: 'r2', exitCode: 1, signal: null, intentional: false, started: true, at: '2026-01-01T00:01:10Z', stderrTail: APPLY_FAILURE_TAIL })
      const patch = await readFile(patchPath, 'utf8')
      expect(patch).not.toContain('disabled: true')
    } finally {
      await supervisor.stop()
      await rm(dir, { recursive: true, force: true })
    }
  })
})