import { describe, expect, it } from 'vitest'
import { createMemoryFs } from '../src/core/fs.ts'
import { quarantinePluginRow, disabledRowText } from '../src/core/plugin-quarantine.ts'

const PATCH = `# AUTO-GENERATED by scripts/aggregate.mjs — do not edit

# from self
- insert:
    - id: web-ui-compat
      name: '@linxin666/dsh-web-all'

# from ../dsh-usage
- insert:
    - id: web-ui-usage
      name: '@linxin666/dsh-web-all'
      config:
        plugin: '@linxin666/dsh-usage'

# from ../dsh-i18n
- insert:
    - id: web-ui-i18n
      name: '@linxin666/dsh-i18n'
`

describe('disabledRowText', () => {
  it('appends a marker comment and a bare disabled row', () => {
    const next = disabledRowText(PATCH, 'web-ui-usage', 'boot failure (apply-message)', '2026-09-01T12:00:00Z')
    expect(next).toContain('# dsh-doctor 2026-09-01T12:00:00Z: auto-quarantined web-ui-usage — boot failure (apply-message)')
    expect(next).toContain('- id: web-ui-usage\n  disabled: true')
    expect(next!.startsWith(PATCH)).toBe(true)
  })

  it('is idempotent: an existing override for the id changes nothing', () => {
    const once = disabledRowText(PATCH, 'web-ui-usage', 'boot failure', '2026-09-01T12:00:00Z')!
    expect(disabledRowText(once, 'web-ui-usage', 'boot failure again', '2026-09-01T13:00:00Z')).toBeUndefined()
  })

  it('does not confuse ids by prefix', () => {
    // web-ui-usage is disabled; web-ui-usages (different row) still gets a row.
    const withUsage = disabledRowText(PATCH, 'web-ui-usage', 'x', '2026-09-01T12:00:00Z')
    expect(disabledRowText(withUsage!, 'web-ui-usag', 'x', '2026-09-01T13:00:00Z')).toBeDefined()
  })

  it('appends a trailing newline when the file lacks one', () => {
    const next = disabledRowText(PATCH.replace(/\n$/, ''), 'web-ui-usage', 'x', 't')
    expect(next).toMatch(/disabled: true\n$/)
  })
})

describe('quarantinePluginRow', () => {
  it('writes the disabled override into the profile patch', async () => {
    const fs = createMemoryFs()
    await fs.mkdir('/home/.dsh/profiles/web', { recursive: true })
    await fs.writeText('/home/.dsh/profiles/web/cordis.patch.yml', PATCH)
    const outcome = await quarantinePluginRow({ home: '/home/.dsh', profile: 'web', rowId: 'web-ui-usage', reason: 'boot failure (apply-message)', fs, now: () => '2026-09-01T12:00:00Z' })
    expect(outcome.phase).toBe('written')
    const text = await fs.readText('/home/.dsh/profiles/web/cordis.patch.yml')
    expect(text).toContain('- id: web-ui-usage\n  disabled: true')
    // Other rows untouched.
    expect(text).toContain("name: '@linxin666/dsh-i18n'")
  })

  it('skips rows this profile does not own (no wrong disables)', async () => {
    const fs = createMemoryFs()
    await fs.mkdir('/home/.dsh/profiles/web', { recursive: true })
    await fs.writeText('/home/.dsh/profiles/web/cordis.patch.yml', PATCH)
    const outcome = await quarantinePluginRow({ home: '/home/.dsh', profile: 'web', rowId: 'web-ui-not-here', reason: 'x', fs })
    expect(outcome.phase).toBe('skipped')
    expect(outcome.message).toContain('not defined by this profile')
  })

  it('skips unparseable patch files (D-040 lane owns those)', async () => {
    const fs = createMemoryFs()
    await fs.mkdir('/home/.dsh/profiles/web', { recursive: true })
    await fs.writeText('/home/.dsh/profiles/web/cordis.patch.yml', '- [broken\n')
    const outcome = await quarantinePluginRow({ home: '/home/.dsh', profile: 'web', rowId: 'web-ui-usage', reason: 'x', fs })
    expect(outcome.phase).toBe('skipped')
  })

  it('skips empty patch files', async () => {
    const fs = createMemoryFs()
    await fs.mkdir('/home/.dsh/profiles/web', { recursive: true })
    await fs.writeText('/home/.dsh/profiles/web/cordis.patch.yml', '[]\n')
    const outcome = await quarantinePluginRow({ home: '/home/.dsh', profile: 'web', rowId: 'web-ui-usage', reason: 'x', fs })
    expect(outcome.phase).toBe('skipped')
  })

  it('reports already when the override exists', async () => {
    const fs = createMemoryFs()
    await fs.mkdir('/home/.dsh/profiles/web', { recursive: true })
    const once = disabledRowText(PATCH, 'web-ui-usage', 'x', 't')
    await fs.writeText('/home/.dsh/profiles/web/cordis.patch.yml', once!)
    const outcome = await quarantinePluginRow({ home: '/home/.dsh', profile: 'web', rowId: 'web-ui-usage', reason: 'x', fs })
    expect(outcome.phase).toBe('already')
  })
})