/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_commands_commands_execute_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_commands_commands_execute_parameter_1$schema = z.string()
const _deepseek_ai_dsh_commands_commands_execute_result$schema = z.union([z.undefined(), z.object({
  'commandId': z.intersection(z.string(), z.unknown()).readonly(),
  'result': z.union([z.object({
  'kind': z.literal("success").readonly(),
  'text': z.string().readonly().optional(),
  'sourceEventSeq': z.number().readonly().optional(),
}), z.object({
  'kind': z.literal("error").readonly(),
  'text': z.string().readonly(),
})]).readonly(),
})])
const _deepseek_ai_dsh_commands_commands_list_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_commands_commands_list_result$schema = z.array(z.object({
  'name': z.string().readonly(),
  'description': z.string().readonly(),
  'input': z.object({
  'hint': z.string().readonly(),
}).readonly().optional(),
}))

export const TYPERT_REMOTE = {
  package: '@deepseek-ai/dsh-commands',
  descriptors: [
    {
      id: '@deepseek-ai/dsh-commands#commands/execute',
      service: 'commands',
      namespace: 'commands',
      method: 'execute',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_commands_commands_execute_parameter_0$schema,
          },
        },
        {
          name: 'line',
          wire: 'line',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-commands#commands/execute:line',
            schema: _deepseek_ai_dsh_commands_commands_execute_parameter_1$schema,
          },
        },
      ],
      cancellation: { parameter: 'signal' },
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-commands#commands/execute:result',
        schema: _deepseek_ai_dsh_commands_commands_execute_result$schema,
      },
      sourceLocation: {"file":"packages/interaction/commands/src/index.ts","line":297,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-commands#commands/list',
      service: 'commands',
      namespace: 'commands',
      method: 'list',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_commands_commands_list_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-commands#commands/list:result',
        schema: _deepseek_ai_dsh_commands_commands_list_result$schema,
      },
      sourceLocation: {"file":"packages/interaction/commands/src/index.ts","line":260,"column":3},
    },
  ],
}

export default TYPERT_REMOTE
