/* Generated by scripts/gallery-build — do not edit by hand. */
window.SKIN_MANIFEST = {
  "generated": "2026-08-19",
  "skins": [
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "blue-fantasy",
      "name": "蓝色幻想",
      "nameEn": "Blue Fantasy",
      "author": "powerdog996（DreamSkin 社区）· dsh-web-ui 适配",
      "tagline": "鲸鱼插画背景 · periwinkle 靛蓝调色板 · 半透明面板",
      "description": "DreamSkin「DeepSeek-鲸鱼娘」Codex 桌面主题的 dsh 适配：鲸鱼插画背景垫在半透明面板之下，遮罩随亮/暗主题实时切换，periwinkle 靛蓝色调重映射到全部 dsh token。",
      "tags": [
        "dreamskin",
        "whale",
        "indigo",
        "art",
        "translucent"
      ],
      "accent": "#4a5fa8",
      "order": 1,
      "version": "0.2.0",
      "preview": {
        "light": "packages/skins/skin-center/skins/blue-fantasy/preview/light.png",
        "dark": "packages/skins/skin-center/skins/blue-fantasy/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css",
        "backgroundMedia": {
          "light": {
            "type": "image",
            "src": "assets/whale-art.jpg",
            "scrim": "linear-gradient(rgba(246, 248, 253, 0.08) 0%, rgba(240, 243, 251, 0.14) 55%, rgba(235, 239, 249, 0.2) 100%)"
          },
          "dark": {
            "type": "image",
            "src": "assets/whale-art.jpg",
            "scrim": "linear-gradient(rgba(10, 14, 28, 0.35) 0%, rgba(13, 18, 34, 0.45) 60%, rgba(16, 22, 42, 0.5) 100%)"
          }
        }
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "whale-song",
      "name": "鲸吟",
      "nameEn": "Whale Song",
      "author": "dsh-web-ui",
      "tagline": "深海鲸语女神背景 · 冰蓝海洋调色板 · 金色细线点缀",
      "description": "《鲸吟》— 深海鲸语女神主题：无文字纯氛围背景画（蓝发女神与鲸群居左、冰蓝星座网格与金线点缀、右侧大量留白）垫在半透明面板之下，遮罩随亮/暗主题实时切换，冰蓝/浅青/深海军蓝/钴蓝冷色体系重映射到全部 dsh token，暗色变体为深海夜航调。",
      "tags": [
        "whale",
        "ocean",
        "ice-blue",
        "goddess",
        "art",
        "translucent"
      ],
      "accent": "#4d8fd4",
      "order": 2,
      "version": "0.2.0",
      "preview": {
        "light": "packages/skins/skin-center/skins/whale-song/preview/light.png",
        "dark": "packages/skins/skin-center/skins/whale-song/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css",
        "backgroundMedia": {
          "light": {
            "type": "image",
            "src": "assets/whale-art.webp",
            "scrim": "linear-gradient(rgba(240, 246, 252, 0.05) 0%, rgba(234, 241, 250, 0.11) 55%, rgba(228, 237, 249, 0.16) 100%)"
          },
          "dark": {
            "type": "image",
            "src": "assets/whale-art.webp",
            "scrim": "linear-gradient(rgba(6, 14, 36, 0.38) 0%, rgba(9, 19, 45, 0.48) 60%, rgba(13, 26, 58, 0.55) 100%)"
          }
        }
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "harbor",
      "name": "夕港",
      "nameEn": "Harbor",
      "author": "moeblack",
      "tagline": "暮光蓝港 · 日落橙辉 · 半透明夜色面板",
      "description": "《夕港》黄昏港口主题：动漫少女黄昏港口背景（暮光蓝天空渐入日落橙）垫在半透明面板之下，遮罩随亮/暗主题实时切换，深暮蓝 #141a2e 底与日落橙 #ff9d5c 主色重映射到 dsh token，亮色是薄暮纱、暗色是深海夜航纱，同一幅画两种读法。",
      "tags": [
        "harbor",
        "dusk",
        "twilight",
        "sunset",
        "amber",
        "art",
        "translucent"
      ],
      "accent": "#ff9d5c",
      "order": 3,
      "version": "0.2.0",
      "preview": {
        "light": "packages/skins/skin-center/skins/harbor/preview/light.png",
        "dark": "packages/skins/skin-center/skins/harbor/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css",
        "backgroundMedia": {
          "light": {
            "type": "image",
            "src": "assets/harbor-art.webp",
            "scrim": "linear-gradient(rgba(20, 26, 46, 0.08) 0%, rgba(20, 26, 46, 0.16) 55%, rgba(20, 26, 46, 0.22) 100%)"
          },
          "dark": {
            "type": "image",
            "src": "assets/harbor-art.webp",
            "scrim": "linear-gradient(rgba(11, 14, 26, 0.42) 0%, rgba(12, 16, 30, 0.52) 60%, rgba(14, 18, 34, 0.6) 100%)"
          }
        }
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "xp",
      "name": "Windows XP (Luna)",
      "nameEn": "Windows XP Luna",
      "author": "dsh-web-ui",
      "tagline": "Luna 蓝窗口条 · 绿色开始按钮 · Bliss 蓝天桌面",
      "description": "Windows XP (Luna) 复古主题：蓝色渐变窗口条带窗口按钮、米色状态栏（大写/数字/滚动指示灯）、侧边栏任务栏上的绿色「开始」按钮、资源管理器风格树行和 Bliss 蓝天桌面，全局直角。",
      "tags": [
        "retro",
        "xp",
        "luna",
        "windows",
        "start-button"
      ],
      "accent": "#316ac5",
      "order": 6,
      "version": "0.2.0",
      "preview": {
        "light": "packages/skins/skin-center/skins/xp/preview/light.png",
        "dark": "packages/skins/skin-center/skins/xp/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css"
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "dragon-heir",
      "name": "龙的传人",
      "nameEn": "Dragon Heir",
      "author": "dsh-web-ui",
      "tagline": "不屈龙魂 · 万里长城双主题 · 朱砂龙印",
      "description": "龙的传人 — 一面是不屈龙魂（墨龙穿云、朱砂印章、不屈锋芒），一面是万里长城（青黛山色、金晖镀墙、苍茫暮色）。亮暗主题各自配一幅画与一枚龙印 favicon，面板半透明磨砂，让画透出来。",
      "tags": [
        "dragon",
        "loong",
        "chinese",
        "ink-wash",
        "great-wall",
        "dual-theme"
      ],
      "accent": "#c3272b",
      "order": 7,
      "version": "0.2.0",
      "preview": {
        "light": "packages/skins/skin-center/skins/dragon-heir/preview/light.png",
        "dark": "packages/skins/skin-center/skins/dragon-heir/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css",
        "backgroundMedia": {
          "light": {
            "type": "image",
            "src": "assets/light-art.webp",
            "scrim": "linear-gradient(rgba(240, 236, 224, 0.05) 0%, rgba(235, 228, 212, 0.09) 55%, rgba(228, 219, 199, 0.14) 100%)"
          },
          "dark": {
            "type": "image",
            "src": "assets/dark-art.webp",
            "scrim": "linear-gradient(rgba(10, 6, 6, 0.14) 0%, rgba(14, 8, 7, 0.2) 60%, rgba(9, 5, 5, 0.24) 100%)"
          }
        }
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "minecraft",
      "name": "Minecraft 方块世界",
      "nameEn": "Minecraft Voxel",
      "author": "dsh-web-ui",
      "tagline": "动态全景天空盒 · 方块按钮 · 告示牌输入框",
      "description": "复刻《我的世界》主界面氛围的方块皮肤：程序化绘制的像素全景天空盒（方块山、像素云、方块树、草方块地面）在身后缓慢旋转，界面浮在石板上；按钮还原 MC 菜单按钮（灰石板、悬停变黄、按下下沉），输入框做成带钉子的木告示牌。",
      "tags": [
        "minecraft",
        "voxel",
        "pixel",
        "game",
        "panorama",
        "skybox"
      ],
      "accent": "#7cbd4b",
      "order": 8,
      "version": "0.2.0",
      "preview": {
        "light": "packages/skins/skin-center/skins/minecraft/preview/light.png",
        "dark": "packages/skins/skin-center/skins/minecraft/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css"
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "trading",
      "name": "交易终端",
      "nameEn": "Trading Terminal",
      "author": "dsh-web-ui",
      "tagline": "实时行情跑马灯 · 长桥港美股行情 · 红涨绿跌交易终端",
      "description": "结合 dsh-fun-ticker 行情跑马灯与 dsh-longbridge 港美股行情的炒股皮肤：顶栏滚动 A股/港股/美股/指数/加密/外汇报价（装 fun-ticker 后跟随你的自选列表），状态栏展示长桥行情快照与 A股/港股/美股交易时段，写代码也像盯盘。",
      "tags": [
        "stock",
        "trading",
        "ticker",
        "live",
        "terminal",
        "longbridge"
      ],
      "accent": "#f23645",
      "order": 9,
      "version": "0.2.0",
      "preview": {
        "light": "packages/skins/skin-center/skins/trading/preview/light.png",
        "dark": "packages/skins/skin-center/skins/trading/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css"
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "miku",
      "name": "初音未来 · 电子歌姬",
      "nameEn": "Hatsune Miku",
      "author": "涂山苏苏",
      "tagline": "蓝紫双马尾 · 01 编号 · 音符波形 · 电子歌姬主题",
      "description": "以世界第一的虚拟歌姬初音未来为灵感的主题皮肤：蓝紫洋红渐变贯穿全局，音符与声波曲线点缀在半透明面板之间，标题栏与状态栏带有 01 编号徽标与音乐波形，半透明毛玻璃面板透出背景图——沉浸式电子歌姬氛围。",
      "tags": [
        "miku",
        "vocaloid",
        "blue",
        "music",
        "idol",
        "waveform"
      ],
      "accent": "#2e9bff",
      "order": 10,
      "version": "0.2.0",
      "preview": {
        "light": "packages/skins/skin-center/skins/miku/preview/light.png",
        "dark": "packages/skins/skin-center/skins/miku/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css",
        "backgroundMedia": {
          "light": {
            "type": "image",
            "src": "assets/miku-art-light.jpg",
            "scrim": "linear-gradient(rgba(244, 250, 255, 0.5) 0%, rgba(235, 244, 255, 0.55) 55%, rgba(226, 238, 255, 0.62) 100%)"
          },
          "dark": {
            "type": "image",
            "src": "assets/miku-art.webp",
            "scrim": "linear-gradient(rgba(4, 10, 28, 0.12) 0%, rgba(6, 14, 36, 0.16) 60%, rgba(8, 18, 42, 0.18) 100%)"
          }
        }
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "whale-mom",
      "name": "鲸鱼妈妈",
      "nameEn": "Whale Mom",
      "author": "dsh-web-ui",
      "tagline": "深海鲸鱼妈妈与幼崽的画作 · 全透面板由背景遮挡驱动 · 金线点缀",
      "description": "dsh web ui 的鲸鱼妈妈主题皮肤：深海鲸鱼妈妈与幼崽们的氛围画作铺满视口，面板全透（透明度由设置-皮肤中心的背景遮挡滑杆驱动，侧边栏基准透明度可用 --dsw-skin-sidebar-alpha 微调），深蓝 / 奶油 / 金色配色贯穿全局，暗色是深海夜航。",
      "tags": [
        "ocean",
        "whale",
        "mother",
        "translucent",
        "gold"
      ],
      "accent": "#d9a53c",
      "order": 11,
      "version": "0.2.0",
      "preview": {
        "light": "packages/skins/skin-center/skins/whale-mom/preview/light.png",
        "dark": "packages/skins/skin-center/skins/whale-mom/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css",
        "backgroundMedia": {
          "light": {
            "type": "image",
            "src": "assets/whale-mom-art.jpg",
            "scrim": "linear-gradient(rgba(18, 28, 56, 0.10) 0%, rgba(20, 30, 60, 0.20) 55%, rgba(24, 34, 66, 0.30) 100%)"
          },
          "dark": {
            "type": "image",
            "src": "assets/whale-mom-art.jpg",
            "scrim": "linear-gradient(rgba(6, 10, 22, 0.42) 0%, rgba(8, 12, 26, 0.52) 60%, rgba(10, 15, 32, 0.62) 100%)"
          }
        }
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "matrix",
      "name": "Matrix 骇客帝国",
      "nameEn": "Matrix",
      "author": "contributed (seanchen)",
      "tagline": "深夜护眼 · 墨绿暗色 · 数字雨",
      "description": "深夜卧室场景的护眼暗色皮肤：近黑墨绿背景、墨绿等宽字体、低透明度数字雨。强制暗色（不跟随系统主题），整体低亮度，长时间使用不刺眼、不打扰家人睡觉。",
      "tags": [
        "matrix",
        "dark",
        "green",
        "hacker",
        "night",
        "eye-care"
      ],
      "accent": "#00e676",
      "order": 12,
      "version": "0.2.0",
      "preview": {
        "light": "packages/skins/skin-center/skins/matrix/preview/light.png",
        "dark": "packages/skins/skin-center/skins/matrix/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css"
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "maid-atelier",
      "name": "深海女仆工坊",
      "nameEn": "Abyssal Maid Atelier",
      "author": "Small-tailqwq",
      "tagline": "双女仆背景、深海蓝蕾丝界面与 Q 版侧栏",
      "description": "一套面向 DeepSeek Harness Web GUI 的高定制动漫角色皮肤。它使用双女仆工坊场景作为对话区背景，以深海蓝、陶瓷白、长春花蓝和柔金构成可热切换的界面覆盖层，并为加载、思考和工具运行状态提供动画反馈。",
      "tags": [
        "anime",
        "maid",
        "whale",
        "navy",
        "ornate",
        "glass"
      ],
      "accent": "#c5a468",
      "order": 13,
      "version": "0.2.0",
      "license": "CC BY-NC-SA 4.0",
      "licenseUrl": "https://github.com/Small-tailqwq/dsh-deep-whale/blob/main/maid-atelier/LICENSE",
      "noticeUrl": "https://github.com/Small-tailqwq/dsh-deep-whale/blob/main/maid-atelier/NOTICE",
      "sourceUrl": "https://github.com/Small-tailqwq/dsh-deep-whale/tree/main/maid-atelier",
      "attribution": "上善 → zipzip → Small-tailqwq",
      "preview": {
        "light": "packages/skins/skin-center/skins/maid-atelier/preview/light.png",
        "dark": "packages/skins/skin-center/skins/maid-atelier/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css"
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "aurora-nebula",
      "name": "极光星舰",
      "nameEn": "Aurora Nebula",
      "author": "Boer2333",
      "tagline": "青·靛·紫极光 · 星点 · 雷达环 · HUD 角标",
      "description": "《极光星舰》— 深空星舰 HUD 主题：青·靛·紫四颗极光光球在深空底色上缓慢漂移，透视网格、确定性星点与同心雷达环构成舰桥视野，HUD 角标与顶部能量线点缀边缘；全部 --dsw-* 语义 token 重映射为青靛紫科技调，暗色为浓烈极光版，浅色为粉彩柔光版。",
      "tags": [
        "aurora",
        "nebula",
        "starship",
        "hud",
        "grid",
        "sci-fi"
      ],
      "accent": "#22d3ee",
      "order": 14,
      "version": "0.1.20",
      "preview": {
        "light": "packages/skins/skin-center/skins/aurora-nebula/preview/light.png",
        "dark": "packages/skins/skin-center/skins/aurora-nebula/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css"
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "summer-liquid-glass",
      "name": "夏沫琉璃",
      "nameEn": "Summer Liquid Glass",
      "version": "0.1.0",
      "author": "dsh-web-ui",
      "tagline": "日系夏祭背景 · iOS 26 液态玻璃 · 冰青玫瑰琥珀三强调",
      "description": "《夏沫琉璃》— 日系夏祭背景 + iOS 26 液态玻璃主题：人物与烟花在分层半透明玻璃面板之后若隐若现，玻璃面板带内缘高光、非均匀边缘反射与柔和扩散阴影；冰青 #67DCE7 作主要交互、玫瑰粉 #DD8FAC 作选中与品牌细节、琥珀金 #F3B75F 作运行中与重要提示、黄绿 #CBE77D 仅用于成功。代码、终端、日志与聊天区使用更低透明度的高可读玻璃，长时间使用不累眼。",
      "tags": [
        "liquid-glass",
        "summer",
        "fireworks",
        "glass",
        "cyan",
        "rose",
        "ios26"
      ],
      "accent": "#67DCE7",
      "order": 14,
      "preview": {
        "light": "packages/skins/skin-center/skins/summer-liquid-glass/preview/light.png",
        "dark": "packages/skins/skin-center/skins/summer-liquid-glass/preview/dark.png"
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css",
        "backgroundMedia": {
          "light": {
            "type": "image",
            "src": "assets/summer-liquid-glass-art.jpg",
            "scrim": "linear-gradient(rgba(7, 19, 33, 0.28) 0%, rgba(7, 19, 33, 0.22) 45%, rgba(7, 19, 33, 0.32) 100%)"
          },
          "dark": {
            "type": "image",
            "src": "assets/summer-liquid-glass-art.jpg",
            "scrim": "linear-gradient(rgba(7, 19, 33, 0.34) 0%, rgba(7, 19, 33, 0.28) 45%, rgba(7, 19, 33, 0.38) 100%)"
          }
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "cyber-neon",
      "name": "赛博霓虹",
      "nameEn": "Cyber Neon",
      "author": "Boer2333",
      "tagline": "品红 × 青蓝霓虹 · synthwave 地网格 · 扫描线",
      "description": "《赛博霓虹》— 赛博朋克终端主题：品红 × 青蓝双霓虹光球、synthwave 透视地网格与扫描线构成夜景终端场景，HUD 角标与顶部能量线强化霓虹边框；全部 --dsw-* 语义 token 重映射为品红·紫·青蓝霓虹调，暗色为浓烈霓虹版，浅色为白瓷粉彩版。",
      "tags": [
        "neon",
        "cyberpunk",
        "synthwave",
        "grid",
        "terminal",
        "retro-futurism"
      ],
      "accent": "#ff2d95",
      "order": 15,
      "version": "0.1.20",
      "preview": {
        "light": "packages/skins/skin-center/skins/cyber-neon/preview/light.png",
        "dark": "packages/skins/skin-center/skins/cyber-neon/preview/dark.png"
      },
      "requires": {
        "contracts": [
          {
            "apiVersion": "x-org.linxin666.skin-center/v1alpha1",
            "kind": "SkinHooks",
            "optional": true
          }
        ]
      },
      "contributes": {
        "stylesheet": "skin.css",
        "patches": "patches.css"
      },
      "facets": {
        "client": {
          "entry": "hooks.mjs",
          "apiVersion": "x-org.linxin666.skin-center/v1alpha1"
        }
      }
    },
    {
      "$schema": "https://schemas.linxin666.org/dsh-skin/v2.json",
      "skinManifestVersion": 2,
      "id": "mint",
      "name": "薄荷",
      "nameEn": "Mint",
      "version": "1.0.0",
      "author": "dsh-web-ui",
      "tagline": "纯 token 范例皮肤 · 零补丁零脚本 · 社区作者的起点模板",
      "description": "薄荷是官方锚定的范例皮肤：只重映射官方 --dsw-alias-* 语义 token（L1），不含 patches.css、hooks.mjs 与背景媒体，展示一个新皮肤所需的全部最小要素。社区作者复制本目录、改颜色、改 id 即可发布一个永远安全的皮肤。",
      "tags": [
        "example",
        "minimal",
        "tokens",
        "mint",
        "template"
      ],
      "accent": "#2fbf8f",
      "order": 99,
      "preview": {
        "light": "packages/skins/skin-center/skins/mint/preview/light.png",
        "dark": "packages/skins/skin-center/skins/mint/preview/dark.png"
      },
      "contributes": {
        "stylesheet": "skin.css"
      }
    }
  ]
};
