/**
 * Host half of the dsh-web family aggregate: the fault-isolation shell.
 * Patch rows generated by scripts/aggregate.mjs mount THIS package and carry
 * the real plugin package name in the row config (`config.plugin`); apply
 * imports and mounts the real module behind an isolation boundary, so one
 * broken plugin degrades alone instead of rolling back the whole boot group.
 * The browser half (./client) carries the compat shim that stamps the legacy
 * DOM hooks (data-pane / data-dsh-frame) the family plugins and skins expect
 * onto current dsh web shells.
 */
import type { Context } from '@deepseek-ai/cordis'
import { apply as shellApply } from './shell.ts'
import type { ShellConfig } from './shell.ts'

/** Required services: none — the shell must activate before anything else. */
export const inject = [] as const

/** Host plugin body: mount the configured real plugin behind the shell boundary. */
export function apply(ctx: Context, config: ShellConfig): Promise<void> {
  return shellApply(ctx, config)
}
