/* Generated by scripts/aggregate.mjs from the aggregate.yml manifest — do not edit.
 * Client-side mirror of the host fault-isolation shell: one entry per
 * shell-wrapped family child that ships a browser client face. The shell
 * folds every family row under this package, and the client module scanner
 * only enumerates loader entries, so without this list the children's
 * client bundles never reach the browser and every family surface
 * (settings sections, cards, docks) vanishes. The aggregate client bundle
 * inlines each child's client module (the tsdown config aliases these
 * specifiers to the child sources) and mounts them as nested client
 * plugins; children that carry their own loader client entry are skipped
 * at runtime (see mountClientChildren in src/client/index.ts).
 */

import * as child0 from '@linxin666/dsh-client-ui-web-ui-settings/client'
import * as child1 from '@linxin666/dsh-client-ui-plugin-manager/client'
import * as child2 from '@linxin666/dsh-client-ui-market/client'
import * as child3 from '@linxin666/dsh-client-ui-task-board/client'
import * as child4 from '@linxin666/dsh-client-ui-git-graph/client'
import * as child5 from '@linxin666/dsh-perf/client'
import * as child6 from '@linxin666/dsh-remote-web-ui/client'
import * as child7 from '@linxin666/dsh-pet/client'
import * as child8 from '@linxin666/dsh-ssh/client'
import * as child9 from '@linxin666/dsh-tool-describe-image/client'
import * as child10 from '@linxin666/dsh-client-ui-skill-explorer/client'
import * as child11 from '@linxin666/dsh-desktop-launcher/client'
import * as child12 from '@linxin666/dsh-doctor/client'
import * as child13 from '@linxin666/dsh-usage/client'
import * as child14 from '@linxin666/dsh-session-archive/client'
import * as child15 from '@linxin666/dsh-client-ui-skin-center/client'

/** The loose shape every child client module must expose at runtime. */
export interface ClientChildModule {
  apply?: unknown
  default?: unknown
  inject?: readonly string[]
}

export interface ClientChild {
  /** Real plugin package name: the cordis plugin name and the key shared
   *  with the family mount-registry guards. */
  name: string
  module: ClientChildModule
}

export const clientChildren: readonly ClientChild[] = [
  { name: '@linxin666/dsh-client-ui-web-ui-settings', module: child0 },
  { name: '@linxin666/dsh-client-ui-plugin-manager', module: child1 },
  { name: '@linxin666/dsh-client-ui-market', module: child2 },
  { name: '@linxin666/dsh-client-ui-task-board', module: child3 },
  { name: '@linxin666/dsh-client-ui-git-graph', module: child4 },
  { name: '@linxin666/dsh-perf', module: child5 },
  { name: '@linxin666/dsh-remote-web-ui', module: child6 },
  { name: '@linxin666/dsh-pet', module: child7 },
  { name: '@linxin666/dsh-ssh', module: child8 },
  { name: '@linxin666/dsh-tool-describe-image', module: child9 },
  { name: '@linxin666/dsh-client-ui-skill-explorer', module: child10 },
  { name: '@linxin666/dsh-desktop-launcher', module: child11 },
  { name: '@linxin666/dsh-doctor', module: child12 },
  { name: '@linxin666/dsh-usage', module: child13 },
  { name: '@linxin666/dsh-session-archive', module: child14 },
  { name: '@linxin666/dsh-client-ui-skin-center', module: child15 },
]
