/**
 * community-index script contract: entry validation rejects malformed
 * registrations, the generated module embeds every entry, and the --check
 * gate stays green against the committed generated file.
 */
import { test } from 'node:test'
import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import { buildOutput, validateEntries } from './community-index'

const VALID = [
  {
    id: 'dsh-a',
    name: 'A',
    nameEn: 'A',
    author: 'author-a',
    description: '描述',
    descriptionEn: 'description',
    repo: 'https://github.com/author-a/dsh-a',
    npm: '@author-a/dsh-a',
    category: 'ui',
  },
  {
    id: 'dsh-b',
    name: 'B',
    nameEn: 'B',
    author: 'author-b',
    repo: 'https://github.com/author-b/dsh-b',
  },
]

test('validateEntries accepts a well-formed list', () => {
  assert.doesNotThrow(() => validateEntries(VALID))
})

test('validateEntries rejects a non-empty array contract violation', () => {
  assert.throws(() => validateEntries([]), /non-empty array/)
  assert.throws(() => validateEntries({}), /non-empty array/)
  assert.throws(() => validateEntries([null]), /must be an object/)
})

test('validateEntries requires the mandatory fields', () => {
  const broken = structuredClone(VALID)
  delete broken[0].repo
  assert.throws(() => validateEntries(broken), /missing required string field repo/)
})

test('validateEntries rejects duplicate ids', () => {
  const dup = structuredClone(VALID)
  dup[1].id = dup[0].id
  assert.throws(() => validateEntries(dup), /duplicate entry id dsh-a/)
})

test('validateEntries requires an https repository URL', () => {
  const bad = structuredClone(VALID)
  bad[0].repo = 'github.com/author-a/dsh-a'
  assert.throws(() => validateEntries(bad), /must be an https:\/\/ URL/)
})

test('validateEntries rejects an unknown category', () => {
  const bad = structuredClone(VALID)
  bad[0].category = 'unknown'
  assert.throws(() => validateEntries(bad), /category must be one of/)
})

test('buildOutput embeds every entry and marks the module auto-generated', () => {
  const out = buildOutput(VALID)
  assert.match(out, /AUTO-GENERATED by scripts\/community-index/)
  assert.match(out, /COMMUNITY_PLUGINS: readonly CommunityPluginEntry\[\]/)
  assert.match(out, /export const COMMUNITY_CATEGORIES = \['ui', 'agent', 'tools', 'knowledge', 'integration', 'security', 'utility'\] as const/)
  assert.match(out, /export type CommunityPluginCategory = typeof COMMUNITY_CATEGORIES\[number\]/)
  const ORDER = ['id', 'name', 'nameEn', 'author', 'repo', 'description', 'descriptionEn', 'npm', 'category']
  for (const entry of VALID) {
    const record = {}
    for (const key of ORDER) {
      if (entry[key] !== undefined) record[key] = entry[key]
    }
    assert.ok(out.includes(JSON.stringify(record)), 'entry missing from output: ' + entry.id)
  }
  // Optional fields stay absent when not provided.
  const bare = {}
  for (const key of ORDER) {
    if (VALID[1][key] !== undefined) bare[key] = VALID[1][key]
  }
  assert.ok(!JSON.stringify(bare).includes('"npm"'), 'npm key must not appear for entries without one')
  assert.ok(!JSON.stringify(bare).includes('"category"'), 'category key must not appear for entries without one')
})

test('--check gate passes against the committed generated file', () => {
  const script = fileURLToPath(new URL('./community-index', import.meta.url))
  const out = execFileSync(process.execPath, [script, '--check'], { encoding: 'utf8' })
  assert.match(out, /check OK/)
})
