/**
 * GENERATED by scripts/skin-hooks-registry.mjs — do not edit.
 * Reviewed market skin hook identities for legacy install recovery.
 */
export interface ReviewedSkinHooksIdentity {
  readonly entry: string
  readonly manifestSha256: string
  readonly hooksSha256: string
}

export const REVIEWED_SKIN_HOOKS: Readonly<Record<string, ReviewedSkinHooksIdentity>> = {
  "abyssal-serenade": {
    entry: "hooks.mjs",
    manifestSha256: "ff9ac39a1e5b6607e0a0795505e9556a1c957e956b50d7dbdeca59e96edcf874",
    hooksSha256: "c920106a33ffabbf235d2f11cbd4d1d55a40bda36a69b154567307eaaa0bf982",
  },
  "blue-fantasy": {
    entry: "hooks.mjs",
    manifestSha256: "b22cc82145e1f90f4257af1411724e34a99513761290980fb5f8d25727809808",
    hooksSha256: "21ac2ad4d4423acf31e3391bfba18ce2d9eec7b192f7a0ba47e8a0c843ff15a5",
  },
  "blueprint": {
    entry: "hooks.mjs",
    manifestSha256: "e36d9d53aae73c4693e36fc2e130bca2996cda6dcd8f80917627897774232a3e",
    hooksSha256: "4f6c7db598e72469920d1dbafd5c20cec39f435f225220ffc860636523ed70bb",
  },
  "cyber-night": {
    entry: "hooks.mjs",
    manifestSha256: "38de22962a80602c22910324e7c5fec171342363760972b7421debeb628d8508",
    hooksSha256: "199f37fe6969e3dfae4891708604b6b639f011068c10356f774145512fd3be69",
  },
  "dragon-heir": {
    entry: "hooks.mjs",
    manifestSha256: "e963197ef3d7b0b444c5976b4dd42cb9e30ce79880bfcb4a076da3426ff60056",
    hooksSha256: "ccc644148fd71cc32723891e97ed586b86fe2f86e0f36362133de7d66d08f5bd",
  },
  "furina": {
    entry: "hooks.mjs",
    manifestSha256: "eaac87525cf305e6a7d78b5257705301fa3818e696c3ccbba205bd72a135f108",
    hooksSha256: "713668d3a50da8878337feb4553f953eea781734934610af37a58dea37112ec9",
  },
  "harbor": {
    entry: "hooks.mjs",
    manifestSha256: "a09949fdf5217ac2f6d5d37603df525e56713385ad799cf4c496fbd71cc5861d",
    hooksSha256: "7981a2f98d1ade2815f7e33e2d79672c280334001a00406bb11b5362ce8182bf",
  },
  "hologram-sanctum": {
    entry: "hooks.mjs",
    manifestSha256: "a655bbde8580eddb45271949a7864355cc5c368f91bd811f3632809134c9c3e8",
    hooksSha256: "f82cf61957efb9d9f53557637b00333aa307b3c9642e73620afdbb1fa9511e9e",
  },
  "maid-atelier": {
    entry: "hooks.mjs",
    manifestSha256: "7596a704bce65006381d27417d4c12bb09d7e5ede038a6f486cfa58e62314aa5",
    hooksSha256: "c4668f9cee8192fe3c25e6a01b779bc9ec9ab1980061106e749551a7bafa4153",
  },
  "matrix": {
    entry: "hooks.mjs",
    manifestSha256: "6bcadb4f3da51a12838e002c8956baac2326bf67d7c1cf1f6108d93f1a7a6485",
    hooksSha256: "2e13e495adabe900df797cdbe930b8cb7fdb2ce721c1ba021e6eb2e74326e551",
  },
  "miku": {
    entry: "hooks.mjs",
    manifestSha256: "a1c713e59ed31eaf43f136205e1326d35419d83d613107423099cef2c992c621",
    hooksSha256: "1c4052d328ac6e1ede3115395e8823c4f6acecd3b4508b85615006a88f7cbdd1",
  },
  "minecraft": {
    entry: "hooks.mjs",
    manifestSha256: "08d4a527db2281e84d919b04392b9101e2c4445dd06746fd8514ac8e0dd3d8c3",
    hooksSha256: "deb4abe5e9dc64b075cb6ab1cfbdb153534a6cf837e3558cc0daee7b1bc6eb1a",
  },
  "orca-link": {
    entry: "hooks.mjs",
    manifestSha256: "48b9c76b6f8fc4fad1473d987c0ebd8c10f4734e2eff2091bbb9040c9a5ce089",
    hooksSha256: "0ea2d7e3f7547d9a37884b788042557ec7c59b1416be527660329584c4d65254",
  },
  "phoebe-atelier": {
    entry: "hooks.mjs",
    manifestSha256: "76cfe0d34f644fcaff6c03dbf84fd82ececf18ef56f3c791a9ab0b5b17a30615",
    hooksSha256: "f39b57db0de26c1b0972cd7160d6197c281c4d66ba6abb6fe193a666da0d5f22",
  },
  "starry-nocturne": {
    entry: "hooks.mjs",
    manifestSha256: "5a5bd138ed156d1877e00ea9acfbf94f8342b751d21796942ed3175562801a61",
    hooksSha256: "5493c9d0c28c80c18e0fe39ee851f3ffe7813f0a126c67c95b36674b2a4bcf65",
  },
  "stellar-diva": {
    entry: "hooks.mjs",
    manifestSha256: "66a56618fbd36da1423d97a0f1196aec391c478f6bdc40fc38f99e23df3dbdbe",
    hooksSha256: "22efa5c0860f8f20c425c79d29a82ee9a98cfb710e2e9c3c6ca633a9eae7086b",
  },
  "trading": {
    entry: "hooks.mjs",
    manifestSha256: "945b5c1f6ef387060a9b7dbb4451a261ecbffedf7949890925cf2b97c6b0c3a8",
    hooksSha256: "76954acbe0925f470fdfc79d60c5402fd11f617342df719382265b70e3f5a36a",
  },
  "war-thunder": {
    entry: "hooks.mjs",
    manifestSha256: "3779eeb27f441deed0be277a5d67342c254305683214bda68fc814565dadab89",
    hooksSha256: "c44435d89e1de3713a2e46da031acc8a1de0cc6502067ba1e1ca2aa3a1d9d88e",
  },
  "whale-mom": {
    entry: "hooks.mjs",
    manifestSha256: "310d99a3f66b8d085830295d2ec5bd979f384d3ea0f785feb01578d5e8e0364f",
    hooksSha256: "be8921f66e7ef6d73a0c12686f9b0134fb1f4d47e38d1dedc09f4a74c1533b83",
  },
  "whale-song": {
    entry: "hooks.mjs",
    manifestSha256: "fa53ef0c536e672fad0448b199f784d22ee7f1a2dd4da6a06c45836800d33331",
    hooksSha256: "beb0f140dab1abb40bda52ad2ae1970feb761e2184e64e1d5810fab7c32dfff3",
  },
  "xp": {
    entry: "hooks.mjs",
    manifestSha256: "8bceb95c45b400b67ceb80a7f063b6c2086c0e9f9907a7b72a592d33017623eb",
    hooksSha256: "1574d30f271f481a681feddc0608b04b0aec684e323fec0b00481f08450e4eb3",
  },
}
