/**
 * GENERATED by scripts/skin-hooks-registry.mjs — do not edit.
 * Reviewed market skin hook identities for legacy install recovery.
 */
export interface ReviewedSkinHooksIdentity {
  readonly entry: string
  readonly manifestSha256: string
  readonly hooksSha256: string
}

export const REVIEWED_SKIN_HOOKS: Readonly<Record<string, ReviewedSkinHooksIdentity>> = {
  "blue-fantasy": {
    entry: "hooks.mjs",
    manifestSha256: "b22cc82145e1f90f4257af1411724e34a99513761290980fb5f8d25727809808",
    hooksSha256: "21ac2ad4d4423acf31e3391bfba18ce2d9eec7b192f7a0ba47e8a0c843ff15a5",
  },
  "cyber-night": {
    entry: "hooks.mjs",
    manifestSha256: "38de22962a80602c22910324e7c5fec171342363760972b7421debeb628d8508",
    hooksSha256: "199f37fe6969e3dfae4891708604b6b639f011068c10356f774145512fd3be69",
  },
  "dragon-heir": {
    entry: "hooks.mjs",
    manifestSha256: "e963197ef3d7b0b444c5976b4dd42cb9e30ce79880bfcb4a076da3426ff60056",
    hooksSha256: "ccc644148fd71cc32723891e97ed586b86fe2f86e0f36362133de7d66d08f5bd",
  },
  "furina": {
    entry: "hooks.mjs",
    manifestSha256: "eaac87525cf305e6a7d78b5257705301fa3818e696c3ccbba205bd72a135f108",
    hooksSha256: "713668d3a50da8878337feb4553f953eea781734934610af37a58dea37112ec9",
  },
  "harbor": {
    entry: "hooks.mjs",
    manifestSha256: "a09949fdf5217ac2f6d5d37603df525e56713385ad799cf4c496fbd71cc5861d",
    hooksSha256: "7981a2f98d1ade2815f7e33e2d79672c280334001a00406bb11b5362ce8182bf",
  },
  "maid-atelier": {
    entry: "hooks.mjs",
    manifestSha256: "f36e854f52f24939dfe6318ed6b1ff6fe33d0564e63255a22aaca459af1a84d9",
    hooksSha256: "8a50922c970337ab07b0843e61b9a771f3a57baf54d18a24e906f13dbb39b4ff",
  },
  "matrix": {
    entry: "hooks.mjs",
    manifestSha256: "6bcadb4f3da51a12838e002c8956baac2326bf67d7c1cf1f6108d93f1a7a6485",
    hooksSha256: "2e13e495adabe900df797cdbe930b8cb7fdb2ce721c1ba021e6eb2e74326e551",
  },
  "miku": {
    entry: "hooks.mjs",
    manifestSha256: "9022628fd39e8ee48aef3b311c12f8411b4cc99d62764e84aa65fb4a5a3631ab",
    hooksSha256: "1c4052d328ac6e1ede3115395e8823c4f6acecd3b4508b85615006a88f7cbdd1",
  },
  "minecraft": {
    entry: "hooks.mjs",
    manifestSha256: "08d4a527db2281e84d919b04392b9101e2c4445dd06746fd8514ac8e0dd3d8c3",
    hooksSha256: "deb4abe5e9dc64b075cb6ab1cfbdb153534a6cf837e3558cc0daee7b1bc6eb1a",
  },
  "orca-link": {
    entry: "hooks.mjs",
    manifestSha256: "48b9c76b6f8fc4fad1473d987c0ebd8c10f4734e2eff2091bbb9040c9a5ce089",
    hooksSha256: "6b0d2c29c5e40840d36a169996113e8b08adfeb83ef882f2248128df7ebe932f",
  },
  "trading": {
    entry: "hooks.mjs",
    manifestSha256: "945b5c1f6ef387060a9b7dbb4451a261ecbffedf7949890925cf2b97c6b0c3a8",
    hooksSha256: "76954acbe0925f470fdfc79d60c5402fd11f617342df719382265b70e3f5a36a",
  },
  "war-thunder": {
    entry: "hooks.mjs",
    manifestSha256: "3779eeb27f441deed0be277a5d67342c254305683214bda68fc814565dadab89",
    hooksSha256: "c44435d89e1de3713a2e46da031acc8a1de0cc6502067ba1e1ca2aa3a1d9d88e",
  },
  "whale-mom": {
    entry: "hooks.mjs",
    manifestSha256: "310d99a3f66b8d085830295d2ec5bd979f384d3ea0f785feb01578d5e8e0364f",
    hooksSha256: "be8921f66e7ef6d73a0c12686f9b0134fb1f4d47e38d1dedc09f4a74c1533b83",
  },
  "whale-song": {
    entry: "hooks.mjs",
    manifestSha256: "fa53ef0c536e672fad0448b199f784d22ee7f1a2dd4da6a06c45836800d33331",
    hooksSha256: "beb0f140dab1abb40bda52ad2ae1970feb761e2184e64e1d5810fab7c32dfff3",
  },
  "xp": {
    entry: "hooks.mjs",
    manifestSha256: "8bceb95c45b400b67ceb80a7f063b6c2086c0e9f9907a7b72a592d33017623eb",
    hooksSha256: "823f25fd5f969feb8e51d8ff1577c1cbecbad847b2abac6e5020fc9ef543663f",
  },
}
