/**
 * Wallpaper Engine HTTP routes for the skin center — the browser half talks
 * to the host through same-origin endpoints under /api/skin-center/we:
 *
 *   GET  /inventory           → JSON wallpaper list (library + import store)
 *   GET  /media/<token>       → video stream (Range supported)
 *   GET  /preview/<token>     → preview image
 *   GET  /web/<token>/<path>  → web-wallpaper project files (HTML is served
 *                               with the WE API shim injected)
 *   GET  /shim.js             → the WE API shim source (we-shim-source.ts)
 *   GET  /scene-frame/<token> → PNG of a scene wallpaper's main texture,
 *                               decoded in-process (pkg-extract.ts), cached
 *                               under the import store's .cache directory
 *   POST /import              → copy a library wallpaper into the import
 *                               store (<harnessHome>/skin-center/wallpapers)
 *   POST /reimport            → refresh an imported copy from its source
 *   POST /remove              → delete an imported copy
 *
 * Tokens are base64url of an absolute path, issued only by the inventory
 * handler, so a crafted token can never reach a path the library scan did
 * not already expose. Every route rides the skin-center same-origin fence
 * (routes.ts) — wallpaper imports must not be triggerable cross-site.
 *
 * Compliance note: this module only ever reads files already present on the
 * user's machine (their own Wallpaper Engine library) or copies them within
 * it. Nothing is downloaded, uploaded, or redistributed.
 * @module @linxin666/dsh-client-ui-skin-center/we-routes
 */

import { cpSync, createReadStream, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import type { IncomingMessage, ServerResponse } from 'node:http'
import { basename, dirname, extname, join as joinPath, resolve as resolvePath, sep } from 'node:path'
import type { WebRoute } from '@deepseek-ai/dsh-host-webserver'
import { json, readJsonBody, requireSameOrigin } from './http-utils.ts'
import {
  buildInventory,
  type WallpaperEntry,
  type WallpaperType,
} from './we-library.ts'
import {
  buildSceneManifest,
  buildSceneManifestFromDir,
  extractSceneResource,
  extractSceneResourceFromDir,
  hasSceneVideo,
  hasSceneVideoFromDir,
  parseTexToRGBA,
} from './pkg-extract.ts'
import { WE_SHIM_JS } from './we-shim-source.ts'
import { WE_SCENE_PLAYER_HTML } from './we-player-source.ts'
import { deflateSync } from 'node:zlib'

/**
 * Scene extraction cache format version, embedded in every frames/videos
 * cache key. The cache keys used to be path + mtime only, so an extraction
 * pipeline change (the #751 projection crop, the #761 TEXI rect crop)
 * never invalidated frames generated by an older build — users who had
 * viewed a wallpaper before the upgrade kept being served the stale frame
 * forever (#792). Bump this whenever the extractor output may change; old
 * cache files then miss, regenerate under the new key, and get pruned.
 */
export const SCENE_EXTRACTOR_VERSION = 2

/**
 * Delete same-wallpaper cache files left by earlier extractor versions or
 * older mtimes, so a version bump does not leave stale debris growing the
 * cache directory forever. The stem comparison is exact: the trailing
 * `[_vN_]<mtime>.<ext>` suffix is stripped first, so one base64url path
 * never prunes another (base64url output can itself contain underscores).
 */
function pruneStaleSceneCache(cacheDir: string, base: string, keep: string): void {
  let entries: string[]
  try { entries = readdirSync(cacheDir) } catch { /* unreadable or absent: nothing to prune */ return }
  for (const name of entries) {
    if (name === keep) continue
    const stem = name.replace(/_(?:v\d+_)?\d+\.[a-z0-9]+$/i, '')
    if (stem === base) {
      try { rmSync(joinPath(cacheDir, name), { force: true }) } catch { /* best effort */ }
    }
  }
}

/**
 * Read a web wallpaper's project.json property defaults so the shim can
 * deliver them like WE does on startup. Values pass through raw: colors stay
 * 'r g b' strings, sliders numbers, checkboxes booleans — exactly what the
 * web API hands to applyUserProperties.
 */
function webPropertyDefaults(projectRoot: string): Record<string, { value: unknown }> {
  const out: Record<string, { value: unknown }> = {}
  try {
    const raw = readFileSync(joinPath(projectRoot, 'project.json'), 'utf8')
    const props = (JSON.parse(raw) as { general?: { properties?: Record<string, { value?: unknown }> } })
      .general?.properties
    if (props) {
      for (const [key, def] of Object.entries(props)) {
        if (def && typeof def === 'object' && 'value' in def) out[key] = { value: def.value }
      }
    }
  } catch { /* no project.json or unreadable: empty defaults */ }
  return out
}

/** Encode RGBA pixel data to PNG buffer using Node zlib for compression. */
function encodeRGBAToPNG(width: number, height: number, rgba: Uint8Array): Buffer {
  // Build raw scanlines: each row prefixed by filter byte 0 (None)
  const rowBytes = width * 4
  const raw = Buffer.alloc(height * (1 + rowBytes))
  for (let y = 0; y < height; y++) {
    raw[y * (1 + rowBytes)] = 0 // filter: None
    raw.set(rgba.slice(y * rowBytes, (y + 1) * rowBytes), y * (1 + rowBytes) + 1)
  }
  const compressed = deflateSync(raw, { level: 1 }) // fast compression

  // PNG CRC32
  const crcTable: number[] = []
  for (let n = 0; n < 256; n++) { let c = n; for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; crcTable[n] = c }
  const crc32 = (buf: Buffer, start: number, len: number): number => {
    let c = 0xffffffff
    for (let i = start; i < start + len; i++) c = crcTable[(c ^ buf[i]) & 0xff] ^ (c >>> 8)
    return (c ^ 0xffffffff) >>> 0
  }

  // Assemble PNG
  const pngSize = 8 + 25 + (12 + compressed.length) + 12 // signature + IHDR + IDAT + IEND
  const png = Buffer.alloc(pngSize)
  let p = 0
  // Signature
  png.set([137, 80, 78, 71, 13, 10, 26, 10], 0); p = 8
  // IHDR
  png.writeUInt32BE(13, p); p += 4
  png.write('IHDR', p); p += 4
  png.writeUInt32BE(width, p); p += 4
  png.writeUInt32BE(height, p); p += 4
  png[p++] = 8 // bit depth
  png[p++] = 6 // RGBA
  png[p++] = 0; png[p++] = 0; png[p++] = 0 // compression, filter, interlace
  png.writeUInt32BE(crc32(png, 12, 17), p); p += 4
  // IDAT
  png.writeUInt32BE(compressed.length, p); p += 4
  png.write('IDAT', p); p += 4
  compressed.copy(png, p); p += compressed.length
  png.writeUInt32BE(crc32(png, p - compressed.length - 4, compressed.length + 4), p); p += 4
  // IEND
  png.writeUInt32BE(0, p); p += 4
  png.write('IEND', p); p += 4
  png.writeUInt32BE(crc32(png, p - 4, 4), p); p += 4

  return png
}

/** Browser-facing base path of the wallpaper API. */
export const WE_API_PREFIX = '/api/skin-center/we'

/** The slice of the skin-wallpaper settings these routes read. */
export interface WeRouteConfig {
  /** Manual library folders (settings field weLibraryDirs). */
  weLibraryDirs?: string[]
}

/** Dependencies the route family needs from the host plugin. */
export interface WeRouteDeps {
  /** Live getter for the skin-wallpaper settings (scope-backed). */
  getConfig: () => WeRouteConfig
  /** Import-store root (<harnessHome>/skin-center/wallpapers). */
  storeDir: string
  /** Auto-detect Steam / Wallpaper Engine installation (default true). */
  autoDetect?: boolean
}

/** Sanitize a wallpaper id into a safe store directory name. */
export function safeStoreId(id: string): string {
  return id.replace(/[^a-zA-Z0-9._-]/g, '_')
}

/** Minimal mime map for wallpaper payloads. */
function mimeFor(absPath: string): string {
  const ext = extname(absPath).slice(1).toLowerCase()
  return {
    mp4: 'video/mp4', webm: 'video/webm', mkv: 'video/x-matroska',
    avi: 'video/x-msvideo', mov: 'video/quicktime',
    html: 'text/html; charset=utf-8', htm: 'text/html; charset=utf-8',
    js: 'text/javascript; charset=utf-8', mjs: 'text/javascript; charset=utf-8',
    css: 'text/css; charset=utf-8', json: 'application/json; charset=utf-8',
    png: 'image/png', jpg: 'image/jpeg', jpeg: 'image/jpeg', gif: 'image/gif',
    webp: 'image/webp', svg: 'image/svg+xml', ico: 'image/x-icon',
    mp3: 'audio/mpeg', wav: 'audio/wav', ogg: 'audio/ogg',
    woff: 'font/woff', woff2: 'font/woff2', ttf: 'font/ttf', otf: 'font/otf',
    wasm: 'application/wasm',
  }[ext] || 'application/octet-stream'
}

/** Stream one file with Range support (video seeking needs 206). */
function serveFile(absPath: string, req: IncomingMessage, res: ServerResponse): void {
  if (!existsSync(absPath) || !statSync(absPath).isFile()) {
    json(res, 404, { ok: false, error: 'not-found' })
    return
  }
  const size = statSync(absPath).size
  res.setHeader('Content-Type', mimeFor(absPath))
  res.setHeader('Accept-Ranges', 'bytes')
  const range = req.headers.range
  if (range) {
    const match = /bytes=(\d*)-(\d*)/.exec(range)
    let start = match && match[1] ? parseInt(match[1], 10) : 0
    let end = match && match[2] ? parseInt(match[2], 10) : size - 1
    if (Number.isNaN(start)) start = 0
    if (Number.isNaN(end) || end >= size) end = size - 1
    if (start > end) {
      res.statusCode = 416
      res.setHeader('Content-Range', 'bytes */' + String(size))
      res.end()
      return
    }
    res.statusCode = 206
    res.setHeader('Content-Range', 'bytes ' + String(start) + '-' + String(end) + '/' + String(size))
    res.setHeader('Content-Length', String(end - start + 1))
    createReadStream(absPath, { start, end }).pipe(res)
    return
  }
  res.setHeader('Content-Length', String(size))
  createReadStream(absPath).pipe(res)
}

/** The JSON shape of one wallpaper entry sent to the browser. */
interface WallpaperJson {
  id: string
  title: string
  type: WallpaperType
  source: WallpaperEntry['source']
  playable: boolean
  updateAvailable: boolean
  videoUrl: string | null
  webUrl: string | null
  frameUrl: string | null
  sceneUrl: string | null
  previewUrl: string | null
}

/** Build the route family. */
export function makeWeRoutes(deps: WeRouteDeps): WebRoute[] {
  // token -> absolute path, issued by the inventory handler only. The map
  // is persisted under the import store cache so issued media URLs survive
  // host restarts without ever accepting a client-supplied path.
  const tokenStorePath = joinPath(deps.storeDir, '.cache', 'we-tokens.json')
  let mediaMap = new Map<string, string>()
  try {
    const saved = JSON.parse(readFileSync(tokenStorePath, 'utf8')) as Record<string, string>
    if (saved !== null && typeof saved === 'object') {
      mediaMap = new Map(Object.entries(saved))
    }
  } catch { /* no store yet: start empty */ }
  const persistTokens = (): void => {
    try {
      mkdirSync(dirname(tokenStorePath), { recursive: true })
      writeFileSync(tokenStorePath, JSON.stringify(Object.fromEntries(mediaMap)), 'utf8')
    } catch { /* best effort; a failed persist only costs token re-issue */ }
  }
  const tokenFor = (absPath: string): string => {
    const token = Buffer.from(absPath, 'utf8').toString('base64url')
    mediaMap.set(token, absPath)
    return token
  }

  const freshInventory = () => buildInventory({
    manualDirs: deps.getConfig().weLibraryDirs ?? [],
    storeDir: deps.storeDir,
    autoDetect: deps.autoDetect,
  })

  // hasVideo / hasSceneWebGL probes parse whole pkgs (LZ4 decompress, tex
  // decode), so cache them by path+mtime+size: /inventory and boot would
  // otherwise re-parse the whole library synchronously on every request.
  const sceneProbeCache = new Map<string, { hasVideo: boolean; hasSceneWebGL: boolean }>()
  const MAX_PROBE_CACHE = 256

  const entryToJson = (entry: WallpaperEntry): WallpaperJson => {
    const hasFile = existsSync(entry.fileAbs)
    let hasVideo = false
    let hasSceneWebGL = false
    if (entry.type === 'scene' && hasFile) {
      let mtimeMs = 0
      let size = 0
      try { const st = statSync(entry.fileAbs); mtimeMs = st.mtimeMs; size = st.size } catch { /* probe once without a key */ }
      const key = entry.fileAbs + ':' + mtimeMs + ':' + size
      let probe = mtimeMs > 0 ? sceneProbeCache.get(key) : undefined
      if (!probe) {
        let hasVideoNow = false
        let hasSceneWebGLNow = false
        try {
          hasVideoNow = entry.fileAbs.toLowerCase().endsWith('.json')
            ? hasSceneVideoFromDir(dirname(entry.fileAbs))
            : hasSceneVideo(new Uint8Array(readFileSync(entry.fileAbs)))
          if (!hasVideoNow) {
            const manifest = entry.fileAbs.toLowerCase().endsWith('.json')
              ? buildSceneManifestFromDir(dirname(entry.fileAbs), 'check')
              : buildSceneManifest(new Uint8Array(readFileSync(entry.fileAbs)), 'check')
            if (manifest && ((manifest.layers && manifest.layers.length >= 1) || (manifest.is3D && manifest.models && manifest.models.length > 0))) {
              hasSceneWebGLNow = true
            }
          }
        } catch {
          hasSceneWebGLNow = false
        }
        probe = { hasVideo: hasVideoNow, hasSceneWebGL: hasSceneWebGLNow }
        if (mtimeMs > 0) {
          if (sceneProbeCache.size >= MAX_PROBE_CACHE) sceneProbeCache.clear()
          sceneProbeCache.set(key, probe)
        }
      }
      hasVideo = probe.hasVideo
      hasSceneWebGL = probe.hasSceneWebGL
    }
    return {
      id: entry.id,
      title: entry.title,
      type: entry.type,
      source: entry.source,
      playable: entry.playable,
      updateAvailable: entry.updateAvailable,
      videoUrl:
        entry.type === 'video' && hasFile
          ? WE_API_PREFIX + '/media/' + tokenFor(entry.fileAbs)
          : hasVideo
            ? WE_API_PREFIX + '/scene-video/' + tokenFor(entry.fileAbs)
            : null,
      webUrl: entry.type === 'web' && hasFile ? WE_API_PREFIX + '/web/' + tokenFor(entry.fileAbs) + '/' : null,
      frameUrl: entry.type === 'scene' && hasFile ? WE_API_PREFIX + '/scene-frame/' + tokenFor(entry.fileAbs) : null,
      sceneUrl: hasSceneWebGL ? WE_API_PREFIX + '/scene-runtime/' + tokenFor(entry.fileAbs) : null,
      previewUrl: entry.previewAbs ? WE_API_PREFIX + '/preview/' + tokenFor(entry.previewAbs) : null,
    }
  }

  /**
   * Resolve a token from a prefix route, or answer 404. Tokens resolve
   * through the issued-token map only: a client-supplied path must never
   * reach the filesystem, otherwise any wallpaper (web wallpapers run
   * arbitrary JS same-origin) could read arbitrary local files.
   */
  const resolveToken = (req: IncomingMessage, res: ServerResponse, prefix: string): string | null => {
    let token = ''
    try {
      const pathname = new URL(req.url || '/', 'http://localhost').pathname
      token = decodeURIComponent(pathname.slice(prefix.length).split('/')[0] ?? '')
    } catch { /* malformed escape sequence: no such token */ }
    const abs = mediaMap.get(token)
    if (!abs) {
      json(res, 404, { ok: false, error: 'unknown-token' })
      return null
    }
    return abs
  }

  const routes: WebRoute[] = []

  // GET /inventory — the wallpaper list; also (re)issues all media tokens.
  routes.push({
    kind: 'exact',
    path: WE_API_PREFIX + '/inventory',
    handler: (req, res) => {
      if (req.method !== 'GET') { json(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      try {
        const inventory = freshInventory()
        const wallpapers = inventory.wallpapers.map(entryToJson)
        persistTokens()
        json(res, 200, {
          ok: true,
          installDir: inventory.installDir,
          total: inventory.total,
          portableCount: inventory.portableCount,
          wallpapers,
        })
      } catch (error) {
        json(res, 500, { ok: false, error: error instanceof Error ? error.message : String(error) })
      }
    },
  })

  // GET /shim.js — the WE API shim for web wallpaper iframes.
  routes.push({
    kind: 'exact',
    path: WE_API_PREFIX + '/shim.js',
    handler: (req, res) => {
      if (req.method !== 'GET') { json(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      res.writeHead(200, { 'content-type': 'text/javascript; charset=utf-8', 'cache-control': 'no-store' })
      res.end(WE_SHIM_JS)
    },
  })

  // GET /media/<token> and /preview/<token> — streamed files.
  for (const seg of ['media', 'preview']) {
    const prefix = WE_API_PREFIX + '/' + seg + '/'
    routes.push({
      kind: 'prefix',
      path: WE_API_PREFIX + '/' + seg,
      handler: (req, res) => {
        if (req.method !== 'GET') { json(res, 405, { ok: false, error: 'method-not-allowed' }); return }
        if (!requireSameOrigin(req, res)) return
        const abs = resolveToken(req, res, prefix)
        if (!abs) return
        // Convert WE .tex files to PNG for browser consumption
        if (abs.toLowerCase().endsWith('.tex')) {
          try {
            const texBuf = readFileSync(abs)
            const result = parseTexToRGBA(new Uint8Array(texBuf.buffer, texBuf.byteOffset, texBuf.byteLength))
            if (result) {
              const pngBuf = encodeRGBAToPNG(result.width, result.height, result.rgba)
              res.writeHead(200, { 'Content-Type': 'image/png', 'Content-Length': pngBuf.length, 'Cache-Control': 'public, max-age=86400' })
              res.end(pngBuf)
              return
            }
          } catch { /* fall through to serveFile */ }
        }
        serveFile(abs, req, res)
      },
    })
  }

  // GET /scene-video/<token> — stream extracted MP4 video from scene pkg textures.
  const sceneVideoPrefix = WE_API_PREFIX + '/scene-video/'
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/scene-video',
    handler: (req, res) => {
      if (req.method !== 'GET') { json(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      const abs = resolveToken(req, res, sceneVideoPrefix)
      if (!abs) return
      void (async () => {
        let mtime = 0
        try { mtime = statSync(abs).mtimeMs } catch { /* stays 0 */ }
        const cacheDir = joinPath(deps.storeDir, '.cache', 'videos')
        const base = Buffer.from(abs, 'utf8').toString('base64url')
        const key = base + '_v' + String(SCENE_EXTRACTOR_VERSION) + '_' + String(Math.round(mtime)) + '.mp4'
        const cachePath = joinPath(cacheDir, key)
        if (!existsSync(cachePath)) {
          const { extractSceneVideo, extractSceneVideoFromDir } = await import('./pkg-extract.ts')
          const videoBytes = abs.toLowerCase().endsWith('.json')
            ? extractSceneVideoFromDir(dirname(abs))
            : extractSceneVideo(new Uint8Array(readFileSync(abs)))
          if (!videoBytes) {
            json(res, 404, { ok: false, error: 'no-video-found' })
            return
          }
          mkdirSync(cacheDir, { recursive: true })
          writeFileSync(cachePath, videoBytes)
          pruneStaleSceneCache(cacheDir, base, key)
        }
        serveFile(cachePath, req, res)
      })().catch((error: unknown) => {
        json(res, 422, { ok: false, error: error instanceof Error ? error.message : String(error) })
      })
    },
  })

  // GET /web/<token>/<subpath> — web-wallpaper project files. The token maps
  // to the entry HTML; subpaths resolve inside its directory only. HTML
  // responses carry the WE API shim ahead of the document.
  const webPrefix = WE_API_PREFIX + '/web/'
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/web',
    handler: (req, res) => {
      if (req.method !== 'GET') { json(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      const pathname = new URL(req.url || '/', 'http://localhost').pathname
      let rest = ''
      try {
        rest = decodeURIComponent(pathname.slice(webPrefix.length))
      } catch { json(res, 400, { ok: false, error: 'bad-request' }); return }
      const token = rest.split('/')[0] ?? ''
      const entryAbs = mediaMap.get(token)
      if (!entryAbs) { json(res, 404, { ok: false, error: 'unknown-token' }); return }
      const root = dirname(entryAbs)
      const sub = rest.slice(token.length).replace(/^\/+/, '') || basename(entryAbs)
      const abs = resolvePath(root, sub)
      if (abs !== root && !abs.startsWith(root + sep)) {
        json(res, 403, { ok: false, error: 'path-escape-rejected' })
        return
      }
      if (!existsSync(abs) || !statSync(abs).isFile()) { json(res, 404, { ok: false, error: 'not-found' }); return }
      if (/\.html?$/i.test(abs)) {
        const html = readFileSync(abs, 'utf8')
        const defaultsTag = '<script>window.__dshWeDefaultProps = ' + JSON.stringify(webPropertyDefaults(root)).replace(/</g, '\\u003c') + ';</script>'
        const tag = defaultsTag + '<script src="' + WE_API_PREFIX + '/shim.js"></script>'
        const injected = /<head[^>]*>/i.test(html)
          ? html.replace(/<head[^>]*>/i, (m) => m + tag)
          : tag + html
        res.writeHead(200, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' })
        res.end(injected)
        return
      }
      serveFile(abs, req, res)
    },
  })

  // GET /scene-frame/<token> — decode the scene pkg's main texture to PNG,
  // cached under <store>/.cache/frames (keyed by path + extractor version +
  // mtime, #792: versionless keys served stale frames across upgrades).
  const framePrefix = WE_API_PREFIX + '/scene-frame/'
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/scene-frame',
    handler: (req, res) => {
      if (req.method !== 'GET') { json(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      const abs = resolveToken(req, res, framePrefix)
      if (!abs) return
      void (async () => {
        let mtime = 0
        try { mtime = statSync(abs).mtimeMs } catch { /* stays 0 */ }
        const cacheDir = joinPath(deps.storeDir, '.cache', 'frames')
        const base = Buffer.from(abs, 'utf8').toString('base64url')
        const key = base + '_v' + String(SCENE_EXTRACTOR_VERSION) + '_' + String(Math.round(mtime)) + '.png'
        const cachePath = joinPath(cacheDir, key)
        if (!existsSync(cachePath)) {
          const { extractSceneMainImage, extractSceneMainImageFromDir } = await import('./pkg-extract.ts')
          // A scene's main file is either the packed container (scene.pkg) or
          // a loose scene.json whose textures live alongside it in the
          // project directory (#521).
          const frame = abs.toLowerCase().endsWith('.json')
            ? extractSceneMainImageFromDir(dirname(abs))
            : extractSceneMainImage(new Uint8Array(readFileSync(abs)))
          mkdirSync(cacheDir, { recursive: true })
          writeFileSync(cachePath, frame.png)
          pruneStaleSceneCache(cacheDir, base, key)
        }
        res.setHeader('Content-Type', 'image/png')
        res.setHeader('Cache-Control', 'no-store')
        createReadStream(cachePath).pipe(res)
      })().catch((error: unknown) => {
        json(res, 422, { ok: false, error: error instanceof Error ? error.message : String(error) })
      })
    },
  })

  // GET /scene-runtime/<token> — serve the WebGL Scene Player HTML runtime.
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/scene-runtime',
    handler: (req, res) => {
      if (req.method !== 'GET') { json(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      res.writeHead(200, { 'content-type': 'text/html; charset=utf-8', 'cache-control': 'no-store' })
      res.end(WE_SCENE_PLAYER_HTML)
    },
  })

  // GET /scene-manifest/<token> — return the JSON manifest of 2D layers and effects.
  const sceneManifestPrefix = WE_API_PREFIX + '/scene-manifest/'
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/scene-manifest',
    handler: (req, res) => {
      if (req.method !== 'GET') { json(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      const abs = resolveToken(req, res, sceneManifestPrefix)
      if (!abs) return
      try {
        const token = Buffer.from(abs, 'utf8').toString('base64url')
        const manifest = abs.toLowerCase().endsWith('.json')
          ? buildSceneManifestFromDir(dirname(abs), token)
          : buildSceneManifest(new Uint8Array(readFileSync(abs)), token)
        if (!manifest) {
          json(res, 404, { ok: false, error: 'manifest-build-failed' })
          return
        }
        json(res, 200, { ok: true, manifest })
      } catch (err) {
        json(res, 500, { ok: false, error: err instanceof Error ? err.message : String(err) })
      }
    },
  })

  // GET /scene-resource/<token>/<subpath> — serve decoded png or asset stream for scene player.
  const sceneResourcePrefix = WE_API_PREFIX + '/scene-resource/'
  routes.push({
    kind: 'prefix',
    path: WE_API_PREFIX + '/scene-resource',
    handler: (req, res) => {
      if (req.method !== 'GET') { json(res, 405, { ok: false, error: 'method-not-allowed' }); return }
      if (!requireSameOrigin(req, res)) return
      const pathname = new URL(req.url || '/', 'http://localhost').pathname
      let rest = ''
      try {
        rest = decodeURIComponent(pathname.slice(sceneResourcePrefix.length))
      } catch { json(res, 400, { ok: false, error: 'bad-request' }); return }
      const token = rest.split('/')[0] ?? ''
      const entryAbs = mediaMap.get(token)
      if (!entryAbs) { json(res, 404, { ok: false, error: 'unknown-token' }); return }
      const subpath = rest.slice(token.length).replace(/^\/+/, '')
      if (!subpath) { json(res, 400, { ok: false, error: 'missing-subpath' }); return }
      try {
        const resBytes = entryAbs.toLowerCase().endsWith('.json')
          ? extractSceneResourceFromDir(dirname(entryAbs), subpath)
          : extractSceneResource(new Uint8Array(readFileSync(entryAbs)), subpath)
        if (!resBytes) {
          json(res, 404, { ok: false, error: 'resource-not-found' })
          return
        }
        // The extractor falls back to raw file bytes when a texture cannot
        // be decoded: label by payload, not by route name.
        const isPng = resBytes.length > 8 && resBytes[0] === 0x89 && resBytes[1] === 0x50 && resBytes[2] === 0x4e && resBytes[3] === 0x47
        res.writeHead(200, { 'content-type': isPng ? 'image/png' : 'application/octet-stream', 'cache-control': 'no-store' })
        res.end(Buffer.from(resBytes))
      } catch (err) {
        json(res, 500, { ok: false, error: err instanceof Error ? err.message : String(err) })
      }
    },
  })

  /** Read the {id} field of a wallpaper POST body. */
  const readId = (body: unknown): string => {
    if (typeof body !== 'object' || body === null) return ''
    const id = (body as Record<string, unknown>).id
    return typeof id === 'string' ? id : ''
  }

  /** Copy one library entry into the import store; dest must not exist. */
  const copyIntoStore = (entry: WallpaperEntry, dest: string): void => {
    mkdirSync(dest, { recursive: true })
    cpSync(entry.dir, joinPath(dest, 'project'), { recursive: true })
    const manifest = {
      sourceId: entry.id,
      title: entry.title,
      type: entry.type,
      srcMtime: entry.srcMtime,
      srcSize: entry.srcSize,
      importedAt: Date.now(),
      file: joinPath('project', entry.file),
      preview: entry.preview ? joinPath('project', entry.preview) : null,
    }
    writeFileSync(joinPath(dest, 'manifest.json'), JSON.stringify(manifest, null, 2), 'utf8')
  }

  /** Register one JSON POST route with the standard error envelope. */
  const postJson = (path: string, run: (id: string, res: ServerResponse) => void): void => {
    routes.push({
      kind: 'exact',
      path,
      handler: (req, res) => {
        if (req.method !== 'POST') { json(res, 405, { ok: false, error: 'method-not-allowed' }); return }
        if (!requireSameOrigin(req, res)) return
        readJsonBody(req).then((body) => run(readId(body), res)).catch((error: unknown) => {
          json(res, 500, { ok: false, error: error instanceof Error ? error.message : String(error) })
        })
      },
    })
  }

  // POST /import — copy a library wallpaper project into the import store.
  postJson(WE_API_PREFIX + '/import', (id, res) => {
    if (id === '' || id.startsWith('imported/')) { json(res, 400, { ok: false, error: 'bad-id' }); return }
    const entry = freshInventory().wallpapers.find((w) => w.id === id)
    if (!entry) { json(res, 404, { ok: false, error: 'wallpaper-not-found' }); return }
    const dest = joinPath(deps.storeDir, safeStoreId(id))
    if (existsSync(dest)) { json(res, 409, { ok: false, error: 'already-imported' }); return }
    copyIntoStore(entry, dest)
    json(res, 200, { ok: true, id: 'imported/' + entry.id })
  })

  // POST /reimport — refresh an imported copy from its (still present) source.
  postJson(WE_API_PREFIX + '/reimport', (id, res) => {
    if (!id.startsWith('imported/')) { json(res, 400, { ok: false, error: 'bad-id' }); return }
    const sourceId = id.slice('imported/'.length)
    const dest = joinPath(deps.storeDir, safeStoreId(sourceId))
    if (!existsSync(dest)) { json(res, 404, { ok: false, error: 'import-not-found' }); return }
    const source = freshInventory().wallpapers.find((w) => w.id === sourceId && w.source !== 'imported')
    if (!source) { json(res, 410, { ok: false, error: 'source-gone' }); return }
    rmSync(dest, { recursive: true, force: true })
    copyIntoStore(source, dest)
    json(res, 200, { ok: true, id })
  })

  // POST /remove — delete an imported copy (never touches the library).
  postJson(WE_API_PREFIX + '/remove', (id, res) => {
    if (!id.startsWith('imported/')) { json(res, 400, { ok: false, error: 'bad-id' }); return }
    const dest = joinPath(deps.storeDir, safeStoreId(id.slice('imported/'.length)))
    if (!existsSync(dest)) { json(res, 404, { ok: false, error: 'import-not-found' }); return }
    rmSync(dest, { recursive: true, force: true })
    json(res, 200, { ok: true })
  })

  return routes
}
